project_name: ncc_b1

img_list: data/mapping_input.txt
model_dir: model/${.project_name}
img_prefix: ""
img_suffix: ""
atlas: data/atlas_norm.npz
multichannel: False

gpu: 1
batch_size: 1
epochs: 1500
steps_per_epoch: 100
load_model: False
initial_epoch: 0
lr: 1e-4
cudnn_nondet: False

enc: [16, 32, 32, 32]
dec: [32, 32, 32, 32, 32, 16, 16]
int-steps: 7
int-downsize: 2
bidir: False

image-loss: ncc
lambda: 0.01

wandb: True
wandb-project: ${project_name}



