project_name: ${dataset}_${image_loss}_${weight}_${norm}

dataset: PostconT1w
# data organization parameters
img_list: data/${dataset}_input.txt
model_dir: model/${project_name}
img_prefix:
img_suffix:
atlas:
multichannel: False
in_order: True

# training parameters
gpu: 1
batch_size: 1
epochs: 1000
steps_per_epoch: 100
load_model: False
initial_epoch: 0
lr: 1e-4
cudnn_nondet: 

# network architecture parameters
enc: [16, 32, 32, 32]
dec: [32, 32, 32, 32, 32, 16, 16]
int_steps: 7
int_downsize: 2
bidir: False

# loss parameters
image_loss: ncc
weight: 0.1
image_loss_weight: 1
norm: l2

wandb: True
wandb_project: ${project_name}

# register folder
moving: data/${dataset}_dataset/test
moved: results/${project_name}/moved
warp: results/${project_name}/warp
result: results/${project_name}/conclude