project_name: ${dataset}_${image_loss}_${norm}_batch${batch_size}

dataset: fbMOLLI_post
# data organization parameters
img_list: data/${dataset}_input.txt
model_dir: model/${project_name}
img_prefix:
img_suffix:
atlas:
multichannel: False
in_order: True

# training parameters
gpu: 1
batch_size: 20
epochs: 1000
steps_per_epoch: 50
load_model: False
initial_epoch: 0
lr: 1e-4
cudnn_nondet: 

# network architecture parameters
enc: [16, 32, 32, 32]
dec: [32, 32, 32, 32, 32, 16, 16]
int_steps: 7
int_downsize: 2
bidir: False

# loss parameters
image_loss: nmi
weight: 0.1
image_loss_weight: 1
norm: l2

mi_config:
  vmin: 0.0
  vmax: 1.0
  num_bins: 128
  sample_ratio: 0.7
  normalised: True

wandb: True
wandb_project: ${project_name}

# register folder
moving: data/${dataset}_dataset/test
inference: results/${project_name}