project_name: Group_${dataset}_${image_loss}_w${weight}_${norm}_${transformation}_cps${bspline_config.cps}_${bspline_config.svf_steps}_${bspline_config.svf_scale}/e${epochs}
path: ${dataset}/group/${image_loss}/${norm}/weight${weight}/${transformation}/cps${bspline_config.cps}_svfsteps${bspline_config.svf_steps}_svfscale${bspline_config.svf_scale}/e${epochs}
dataset: fbMOLLI_post
# data organization parameters
img_list: data/${dataset}_input.txt
model_dir: model/${path}
img_prefix:
img_suffix:
atlas: True
atlas_methods: pca
multichannel: False
in_order: True

# training parameters
gpu: 1
batch_size: 1
epochs: 100
steps_per_epoch: 10
load_model: False
model_path: model/${path}/500.pt
initial_epoch: 0
lr: 1e-4
cudnn_nondet:

# network architecture parameters
enc: [32, 64, 64, 64]
dec: [64, 64, 64, 64, 32, 32, 16, 16]
int_steps: 7
int_downsize: 2
bidir: False

# loss parameters
image_loss: jointcorrelation
weight: 0.5
image_loss_weight: 1
norm: l2

mi_config:
  vmin: 0.0
  vmax: 1.0
  num_bins: 128
  sample_ratio: 0.7
  normalised: True

# transform parameters
transformation: bspline
bspline_config:
  cps: 4
  svf: True
  svf_steps: 7
  svf_scale: 1
  resize_channels: [64, 32]

log: wandb
wandb_project: ${project_name}

# register folder
moving: data/${dataset}_dataset/test
inference: results/${path}
